#!/usr/bin/env bash
# This script that will display information about subdomains
print_information ()
{
    echo "The subdomain $2 is a "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    echo " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}
if [ -z "$2" ]
then
   for i in "www" "lb-01" "web-01" "web-02"
   do
       print_information "$1" "$i"
   done
else
    print_information "$1" "$2"
fi
