#!/usr/bin/env bash
# This script transfers a file from our client to a server
sudo apt-get update
sudo apt-get install -y nginx

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart
