#!/usr/bin/env bash
# This script transfers a file from our client to a server
sudo apt-get update
sudo apt-get install -y nginx

# sudo ufw status

# sudo chown -R $USER:$USER /var/www/html
# sudo chmod -R 755 /var/www

# cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
