#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01 server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*
echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 459640-web-01 52.91.147.15:80 check
   server 459640-web-02 52.91.147.53:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
