#!/usr/bin/env bash
# Updated code of 0-nginx_likes_port_80
ln --symbolic --force /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
